version: 2

git:
  ignore_tags:
    - "nightly"

builds:
  - id: schemafixer
    main: ./cmd/schemafixer
    binary: schemafixer
    ldflags:
      - -s -w -X main.version={{.Version}} -extldflags=-static
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64

archives:
  - id: schemafixer
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

sboms:
  - artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.json

release:
  prerelease: auto  # detecteert '-rc' automatisch

dockers:
  - image_templates:
      - "devbfvio/schemafixer:{{ .Version }}"
      - "devbfvio/schemafixer:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/bfv/schemafixer"
    extra_files:
      - README.md
      - LICENSE
