version: 2

builds:
  - id: schemafixer
    main: ./cmd/schemafixer
    binary: schemafixer
    ldflags:
      - -X main.version={{.Version}} -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64

archives:
  - id: schemafixer
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

sboms:
  - artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.json

release:
  prerelease: auto  # detecteert '-rc' automatisch
  